# Generated by Django 2.2.6 on 2020-04-28 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trolley', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trolleyorderitem',
            name='color_drawer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.DrawerColor'),
        ),
    ]
