# Generated by Django 2.2.6 on 2020-04-28 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trolley', '0002_auto_20200428_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trolleyorderitem',
            name='castor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='castor_stock', to='backend.Castor'),
        ),
    ]
