# Generated by Django 2.2.6 on 2020-05-01 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_strip'),
        ('trolley', '0003_auto_20200428_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='trolleyorderitem',
            name='strip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Strip'),
        ),
        migrations.AlterField(
            model_name='trolleyorderitem',
            name='castor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='castor_stock', to='backend.Castor'),
        ),
        migrations.AlterField(
            model_name='trolleyorderitem',
            name='color_drawer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.DrawerColor'),
        ),
        migrations.AlterField(
            model_name='trolleyorderitem',
            name='color_side',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='color_drawer', to='backend.Color'),
        ),
        migrations.AlterField(
            model_name='trolleyorderitem',
            name='wall_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.WallType'),
        ),
    ]
