# Generated by Django 2.2.6 on 2020-05-03 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trolley', '0004_auto_20200502_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='trolleyorderitem',
            name='position',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
