# Generated by Django 2.2.6 on 2020-05-07 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0004_auto_20200506_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheetitem',
            name='description',
        ),
    ]
