# Generated by Django 2.2.6 on 2020-04-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='width',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
