# Generated by Django 2.2.6 on 2020-04-28 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200428_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='width',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
