# Generated by Django 2.2.6 on 2020-04-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20200428_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='width',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
