# Generated by Django 2.2.6 on 2020-04-28 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Location'),
        ),
    ]
