# Generated by Django 2.2.6 on 2020-04-30 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20200428_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
        migrations.AddField(
            model_name='client',
            name='b_client',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
