# Generated by Django 2.2.6 on 2020-05-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_contact_nif'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='nif',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
