# Generated by Django 2.2.6 on 2020-04-29 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adjust', '0002_auto_20200430_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustfavorite',
            name='stock',
            field=models.TextField(blank=True),
        ),
    ]
